Revise to not erase bin/cue on failures (other than "expected" failures). check_common_fn: add common routine check results and report results

diff --git a/tests/check_common_fn b/tests/check_common_fn
--- a/tests/check_common_fn
+++ b/tests/check_common_fn
@@ -51,6 +51,22 @@ have_cksum() {
     return 0;
 }
 
+check_result() {
+  RC=$1
+  shift
+  msg=$*
+  if test $RC -ne 0 ; then 
+    if test $RC -ne 77 ; then
+      echo "$0: $msg failed."
+      exit $RC
+    else 
+      echo "$0: $msg skipped."
+    fi
+  else 
+    echo "$0: $msg ok."
+  fi
+}
+
 #;;; Local Variables: ***
 #;;; mode:shell-script ***
 #;;; eval: (sh-set-shell "bash") ***
